spring.application.name=Hotel_Booking


#Neon Production Database
# Spring Datasource Configuration for Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-steep-river-b3kfy7a8-pooler.c-4.ap-southeast-1.aws.neon.tech/booking?sslmode=require&channelBinding=require
spring.datasource.username=booking_owner
spring.datasource.password=*************
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




# H2 test Database
